[features]
seeds = false
[programs.localnet]
mysolanaapp = "KhPFzL3CyCu47XAybg4PPZnxtzaowX6agv6EvmK6p1u"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/taqi/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
